global:
  resolve_timeout: 5m

route:
  group_by: ['job']
  group_wait: 30s
  group_interval: 1m
  repeat_interval: 1m
  receiver: 'webhook'
  routes: []

receivers:
  - name: "webhook"
    webhook_configs:
      - url: http://http-server:8080
        send_resolved: true
