version: "3.7"

volumes:
  prometheus_data: {}

networks:
  back-tier:

services:
  prometheus:
    image: prom/prometheus:v2.45.0
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
      - "--web.enable-admin-api"
    ports:
      - 9090:9090
    links:
      - alertmanager:alertmanager
      - node-exporter-ubuntu:node-exporter-ubuntu
    depends_on: []
    networks:
      - back-tier
    restart: always

  node-exporter-ubuntu:
    image: ubuntu:mantic
    command: /bin/bash -c "apt-get update && apt-get install -y curl && \
      curl -LO https://github.com/prometheus/node_exporter/releases/download/v1.6.1/node_exporter-1.6.1.linux-amd64.tar.gz && \
      tar xvfz node_exporter-1.6.1.linux-amd64.tar.gz && \
      mv node_exporter-1.6.1.linux-amd64/node_exporter /usr/local/bin/ && \
      rm -rf node_exporter-1.6.1.linux-amd64* && \
      /usr/local/bin/node_exporter --collector.filesystem.fs-types-exclude='^devfs$'"
    ports:
      - '9100:9100'
    networks:
      - back-tier
    restart: always

  alertmanager:
    image: prom/alertmanager
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    networks:
      - back-tier
    restart: always
    links:
      - http-server:http-server
    command:
      - "--config.file=/etc/alertmanager/config.yml"
      - "--storage.path=/alertmanager"

  http-server:
    build: ./http_server/.
    environment:
      - SERVER_PORT=8080
    ports:
      - 8080:8080
    volumes:
      - ./http_server/server.log:/app/server.log:rw
    networks:
      - back-tier
    restart: always
